"use client";

import React, { useCallback, useEffect, useMemo } from "react";
import { cn } from "../utils/cn";
import { useCopyFeedback } from "../utils/use-copy-feedback";
import { Button } from "../components/button";
import { useShikiHighlighter } from "./use-shiki-highlighter";
import type { CodeHighlightedProps } from "./types";

/**
 * Syntax-highlighted code block powered by Shiki.
 *
 * Must be used within a ShikiProvider. While Shiki is loading,
 * displays code as plain text (no layout shift, immediately readable).
 *
 * Uses hardcoded themes: `github-light` for light mode, `vesper` for dark mode.
 *
 * @example
 * ```tsx
 * import { ShikiProvider, CodeHighlighted } from "@cloudflare/kumo/code";
 *
 * <ShikiProvider
 *   engine="javascript"
 *   languages={['tsx', 'bash']}
 * >
 *   <CodeHighlighted
 *     code={`const greeting = "Hello!";`}
 *     lang="tsx"
 *     showLineNumbers
 *     showCopyButton
 *   />
 * </ShikiProvider>
 * ```
 */
export function CodeHighlighted({
  code,
  lang,
  variant = "default",
  showLineNumbers = false,
  highlightLines,
  showCopyButton = false,
  labels: labelOverrides,
  className,
}: CodeHighlightedProps): React.JSX.Element {
  const {
    highlight,
    isLoading,
    error,
    labels: providerLabels,
  } = useShikiHighlighter();
  const { copied, runCopy } = useCopyFeedback();

  // Merge provider labels with component-level overrides
  const labels = useMemo(
    () => ({ ...providerLabels, ...labelOverrides }),
    [providerLabels, labelOverrides],
  );

  const handleCopy = useCallback(async () => {
    await runCopy(
      () => navigator.clipboard.writeText(code),
      (error) =>
        console.error(
          "[Kumo CodeHighlighted] Failed to copy to clipboard:",
          error,
        ),
    );
  }, [code, runCopy]);

  // Memoized so unrelated rerenders (e.g. copy state) don't re-highlight
  const html = useMemo(() => highlight(code, lang), [highlight, code, lang]);

  // Count lines for line numbers
  const lineCount = useMemo(() => code.split("\n").length, [code]);

  // Detect single-line code for layout adjustments
  const isSingleLine = lineCount === 1;

  // Container styles - use flex layout for single-line with copy button
  // Includes defensive resets (m-0, p-0) to prevent global CSS pollution
  const containerClasses = cn(
    "group relative m-0 w-full min-w-0 p-0",
    variant === "plain"
      ? "rounded-none border-0 bg-transparent"
      : "rounded-md border border-kumo-fill bg-kumo-base",
    showCopyButton && isSingleLine && "flex items-center",
    className,
  );

  const fallbackCodeClasses = cn(
    // Prevent global pre styles from affecting the loading and error states.
    "!m-0 min-w-0 flex-1 overflow-x-auto",
    "font-mono text-sm leading-relaxed text-kumo-subtle",
    variant === "plain" ? "!p-0" : "!p-4",
  );

  const highlightedCodeClasses = cn(
    "kumo-shiki",
    // Reset the code element generated by Shiki.
    "[&_code]:!m-0 [&_code]:!border-0 [&_code]:!bg-transparent [&_code]:!p-0",
    // Let the Kumo container provide the frame and background.
    "[&>pre]:!m-0 [&>pre]:!rounded-none [&>pre]:!border-0 [&>pre]:!bg-transparent",
    "[&>pre]:font-mono [&>pre]:text-sm [&>pre]:leading-relaxed",
    variant === "plain" ? "[&>pre]:!p-0" : "[&>pre]:!p-4",
    // Highlighted lines normally extend into the default padding. A plain
    // block has no padding, so keep its highlights within the content width.
    variant === "plain" &&
      "[&_.line-highlighted]:!m-0 [&_.line-highlighted]:!w-full [&_.line-highlighted]:!px-0",
  );

  // Copy button - inline for single-line, absolute for multi-line
  // Hidden until hover (or when showing "Copied!" feedback)
  const copyButton = showCopyButton ? (
    <div
      className={cn(
        isSingleLine
          ? "shrink-0 px-2"
          : variant === "plain"
            ? "absolute top-0 right-0"
            : "absolute top-2 right-2",
        !copied && "opacity-0 transition-opacity group-hover:opacity-100",
      )}
    >
      <Button
        variant="secondary"
        size="sm"
        onClick={handleCopy}
        aria-label={copied ? labels.copied : labels.copy}
      >
        {copied ? labels.copied : labels.copy}
      </Button>
    </div>
  ) : null;

  // Line numbers column
  const lineNumbers =
    showLineNumbers && !isSingleLine ? (
      <div
        className={cn(
          "kumo-line-numbers shrink-0 pr-4 text-right font-mono text-sm opacity-40 select-none",
          variant === "plain" ? "py-0" : "py-4",
        )}
        aria-hidden="true"
      >
        {Array.from({ length: lineCount }, (_, i) => (
          <div key={i + 1} className="leading-relaxed">
            {i + 1}
          </div>
        ))}
      </div>
    ) : null;

  // Still show the code on error; log once per error, not every render
  useEffect(() => {
    if (error) {
      console.error(
        "[Kumo CodeHighlighted] Shiki initialization error:",
        error,
      );
    }
  }, [error]);

  // Loading or failed to highlight — show plain text
  if (isLoading || html === null) {
    return (
      <div className={containerClasses}>
        {lineNumbers && (
          <div className="flex">
            {lineNumbers}
            <pre className={fallbackCodeClasses}>
              <code className="!m-0 !p-0">{code}</code>
            </pre>
          </div>
        )}
        {!lineNumbers && (
          <pre className={fallbackCodeClasses}>
            <code className="!m-0 !p-0">{code}</code>
          </pre>
        )}
        {copyButton}
      </div>
    );
  }

  // Highlighted code
  return (
    <div className={containerClasses}>
      {lineNumbers && (
        <div className="flex w-full">
          {lineNumbers}
          <div className="min-w-0 flex-1 overflow-x-auto">
            <div
              className={highlightedCodeClasses}
              dangerouslySetInnerHTML={{
                __html: processHighlightedHtml(html, highlightLines),
              }}
            />
          </div>
        </div>
      )}
      {!lineNumbers && (
        <div className="overflow-x-auto">
          <div
            className={highlightedCodeClasses}
            dangerouslySetInnerHTML={{
              __html: processHighlightedHtml(html, highlightLines),
            }}
          />
        </div>
      )}
      {copyButton}
    </div>
  );
}

CodeHighlighted.displayName = "CodeHighlighted";

/**
 * Process Shiki's HTML output to add line highlighting classes.
 * Does NOT modify Shiki's token structure - only adds classes to line spans.
 */
function processHighlightedHtml(
  html: string,
  highlightLines?: number[],
): string {
  // Line numbers are not yet supported - would require more complex approach
  // For now, only handle line highlighting which just adds a class

  if (!highlightLines?.length) {
    return html;
  }

  const highlightSet = new Set(highlightLines);
  let lineNumber = 0;

  // Only add the highlight class to lines, don't restructure the HTML
  return html.replace(/<span class="line">/g, () => {
    lineNumber++;
    const isHighlighted = highlightSet.has(lineNumber);
    return isHighlighted
      ? '<span class="line line-highlighted">'
      : '<span class="line">';
  });
}
